---
- hosts: localhost

  tasks:
    - name: Update pacman database
      shell: sudo pacman -Syu --noconfirm
    - name: Cloning paru
      shell: sudo pacman -S --needed base-devel; git clone https://aur.archlinux.org/paru.git ~/Repos/paru -p
    - name: Install paru
      shell: cd ~/Repos/paru; makepkg -si --noconfirm
    - name: Config key sublime
      shell: curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg; echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
    - name: Install program
      shell: cat ~/Repos/dotfiles/arch/packages/program.list | xargs sudo paru -S --noconfirm
    - name: Active systemd
      shell: ~/Repos/dotfiles/arch/enable_service
    - name: Clean up
      shell: pacman -Qtdq | sudo pacman -Rns -; sudo pacman -Syu
