- name: Ensure Repos directory exists.
  file:
    dest: "{{ repos }}"
    mode: 0700
    state: directory

- name: Clonning paru
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: "{{ repos }}/paru"
    clone: yes
    update: yes

- name: Install paru
  become: true
  ansible.builtin.shell:
    cmd: makepkg -si --needed --noconfirm
    chdir: "{{ repos }}/paru"

- name: Cleaning up paru
  file:
    dest: "{{ repos }}/paru"
    state: absent
