- name: Add sublime-text key
  shell: curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg

- name: Run the equivalent of "pacman -Syu"
  become: true
  become_user: root
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install sublime-text
  become: true
  become_user: root
  community.general.pacman:
    name: sublime-text
    state: latest
